# Generated by Django 4.1 on 2022-12-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=126)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
