# Generated by Django 4.1 on 2022-12-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidades',
            old_name='id_cidade',
            new_name='idcidade',
        ),
        migrations.RenameField(
            model_name='cidades',
            old_name='nome_cidade',
            new_name='nomecidade',
        ),
    ]
