# Generated by Django 4.1 on 2022-12-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_id_cidade_cidades_idcidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidades',
            old_name='idcidade',
            new_name='id_cidade',
        ),
        migrations.RenameField(
            model_name='cidades',
            old_name='nomecidade',
            new_name='nome_cidade',
        ),
    ]
